# Blog info
blog_name: Camel Qu
slogan: Java is the best lan... XoX
url: http://www.lightcode.club

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: Java dog

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/CamelQu
    target_blank: true
  - name: Weibo
    url: http://weibo.com/camelqu
    target_blank: true
  - name: About
    url: /about
    target_blank: false

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: ROUND_RECT  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Java真的是世界上最好的...XoX

link_slogan:
  isShow: false # true|fase
  text:

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics:

# Comment service
disqus_shortname: forsigner
# duoshuo_shortname: forsigner


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "就是一只Java狗"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@CamelQu"
    text_value_url: https://github.com/CamelQu
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@目目住面对很多impossible"
    text_value_url: http://weibo.com/camelqu
  - type: mail
    icon: icon-mail
    text_key: E-mail
    text_value: "ymhd318@163.com"
  - type: location
    icon: icon-location
    text_value: 杭州
